import { Navbar } from '@/components/navbar/Navbar'
import { Container, Dados, Foto } from '@/styles'
import Head from 'next/head'
import Image from 'next/image'

import me from '../assets/me.jpg'
import { useEffect, useState } from 'react'
import Link from 'next/link'

export default function Home() {

  const [text, setText] = useState('');
  const [showBlinkingSpan, setShowBlinkingSpan] = useState(false);

  useEffect(() => {
    let fullText = 'Beenjamin Inácio';
    let currentIndex = 0;

    const typingInterval = setInterval(() => {
      setText((prevText) => prevText + fullText[currentIndex]);
      currentIndex++;


      if (currentIndex === fullText.length - 1) {
        clearInterval(typingInterval);
        setShowBlinkingSpan(true);
      }
    }, 150);

    return () => {
      clearInterval(typingInterval);
    };
  }, []);

  useEffect(() => {
    const blinkInterval = setInterval(() => {
      setShowBlinkingSpan((prevValue) => !prevValue);
    }, 500);

    return () => {
      clearInterval(blinkInterval);
    };
  }, []);


  return (
    <>
      <Head>
        <title>BenDev Portifólio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Navbar />
      <Container>
      <Dados>
      <h1>{text}
      {showBlinkingSpan && <span className="blinking-span">_</span>}
      </h1>
      <p>
       <span>Desenvolvedor</span> e estudante de análise e desenvolvimento de sistemas
      </p>
      <br></br>
      <div>
        <p>Atualmente trabalhando na empresa: <span><Link href="https://www.linkedin.com/company/the-brooklyn-brothers/mycompany/">The brooklyn brothers</Link></span></p>
        <br></br>
        <p>Faculdade: <span>UNIP</span>
        </p>
        
        <br></br>
        <p>Localização: <span>São Paulo - SP</span></p>
        <br></br>
        <p>Idade: <span>20 anos</span></p>
        <br></br>
        <p>Natural de: <span>Maceió - Alagoas</span> <br></br><br></br>
        <span>Explore a barra de navegação para ver as minhas skills :)</span>
        </p>
      </div>
      </Dados>
      <Foto>
        <Image src={me.src} alt="Homem de pele escura usando óculos e boné"
          width={400} height={400}
        ></Image>
      </Foto>
      </Container>
    </>
  )
}
