import { Navbar } from '@/components/navbar/Navbar'
import { Container, Dados, Foto } from '@/styles'
import Head from 'next/head'
import Image from 'next/image'

import me from '../assets/me.jpg'
import logoUnip from '../assets/logoUnip.png'

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"></link>
        <link href="https://fonts.googleapis.com/css2?family=Overpass:wght@300;400;500;700&display=swap" rel="stylesheet"></link>
      </Head>
      <Navbar />
      <Container>
      <Dados>
      <h1>
        Benjamin Inácio
      </h1>
      <p>
       <span>Desenvolvedor</span> e estudante de análise e desenvolvimento de sistemas
      </p>
      <br></br>
      <div>
        <p>Atualmente trabalhando na empresa:</p>
        <br></br>
        <p>Faculdade: Unip
        </p>
        
        <br></br>
        <p>Localização: São Paulo - SP</p>
        <br></br>
        <p>Idade: 20 anos</p>
        <br></br>
        <p>Natural de: Maceió - Alagoas</p>
      </div>
      </Dados>
      <Foto>
        <Image src={me.src} alt="Homem de pele escura usando óculos e boné"
          width={400} height={400}
        ></Image>
      </Foto>
      </Container>
    </>
  )
}
