import { Navbar } from '@/components/navbar/Navbar'
import { Container, Dados, Foto } from '@/styles'
import Head from 'next/head'
import Image from 'next/image'

import me from '../assets/me.jpg'

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Container>
      <Dados>
      <h1>
        Benjamin Inácio
      </h1>
      <p>
        Desenvolvedor e estudante de análise e desenvolvimento de sistemas
      </p>
      <br></br>
      <p>Atualmente trabalhando na empresa:</p>
      <br></br>
      <p>Faculdade:</p>
      <br></br>
      <p>Localização:</p>
      <br></br>
      <p>Idade:</p>
      <br></br>
      <p>Natural de:</p>
      </Dados>
      <Foto>
        <Image src={me.src} alt="Homem de pele escura usando óculos e boné"
          width={400} height={400}
        ></Image>
      </Foto>
      </Container>
    </>
  )
}
